# **Numpy**

   - What is NumPy?

    - NumPy is a free, open-source library for Python that adds support for large, multi-dimensional arrays and mathematical functions.

In [1]:
# install numpy

!pip install numpy

In [2]:
# how to import numpy

import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [4]:
# creating numpy in (0D)

arr = np.array(54)

print(arr)

54


In [5]:
# creating numpy in (1D)

arr = np.array([1,2,3,4,6,7])

print(arr)

[1 2 3 4 6 7]


In [7]:
# creating numpy in (2D)

arr = np.array([[1,3,5],
                [4,5,7]])

print(arr)

[[1 3 5]
 [4 5 7]]


In [9]:
# credating numpy in (3D)

arr = np.array([[[13,54,76],
                 [21,54,56],
                  [12,43,67]]])
print(arr)

[[[13 54 76]
  [21 54 56]
  [12 43 67]]]


In [10]:
# creating numpy in (4D)

arr = np.array([[[[21,23,57],
                  [12,34,56],
                  [23,66,77]]]])

print(arr)

[[[[21 23 57]
   [12 34 56]
   [23 66 77]]]]


In [11]:
# creating numpy in (5D)

arr = np.array([[[[[32,54,43],
                   [12,34,67],
                   [12,45,67]]]]])

print(arr)

[[[[[32 54 43]
    [12 34 67]
    [12 45 67]]]]]


# **Initial place holders**

In [14]:
# creating intial place holder with zeros

arr = np.zeros([4,3,3])

print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [4]:
# creating intial place holders with ones
import numpy as np
arr = np.ones([3,4,3])

print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [17]:
# creating an array of evely space value (step value)
# steps = n-1 (n=3)

arr = np.arange(1,50,3)
print(arr)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [5]:
# n-1(n=4)

c = np.arange(1,40,4)

print(c)

[ 1  5  9 13 17 21 25 29 33 37]


In [7]:
# exmalpes

a = np.array([[[2,4,6],[4,7,9],
               [2,4,6],[4,8,3],
               [9,5,7],[3,9,1]]])

print(a)

[[[2 4 6]
  [4 7 9]
  [2 4 6]
  [4 8 3]
  [9 5 7]
  [3 9 1]]]


In [8]:
b = np.array([[23,5,45],[6,9,23],
              [45,7,3],[65,3,87],
              [34,67,5],[56,5,4]])

print(b)

[[23  5 45]
 [ 6  9 23]
 [45  7  3]
 [65  3 87]
 [34 67  5]
 [56  5  4]]


In [9]:
import numpy as np

In [10]:
!pip install numpy

In [12]:
# creating constant array
# 1D
r = np.full((2),12)  # coloums
print(r)
print(r.ndim)

[12 12]
1


In [16]:
# 2D
a = np.full((5,4),2)
print(a)
print(a.ndim,"no of dimesions")

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
2 no of dimesions


In [17]:
# 3D

m = np.full((2,5,4),3)
print(m)
print(a.ndim)

[[[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]

 [[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]]
2


# **Identity matrix**

In [19]:
# creating identity matrix
r = np.eye(7)
print(r)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [26]:
# creating an array with random values

np.random.random((1,20))

array([[0.16805504, 0.00594626, 0.66987751, 0.89377256, 0.83075825,
        0.55713854, 0.94109412, 0.51763621, 0.3821741 , 0.69654538,
        0.28207515, 0.08345453, 0.4337834 , 0.39761702, 0.99083468,
        0.5692339 , 0.13316863, 0.74326778, 0.93043733, 0.75061459]])

In [29]:
# creating an array with random integer values
np.random.randint(2,56)

9

# **Array Attributes**

  - In NumPy, attributes are properties of NumPy arrays that provide information about the array's shape, size, data type, dimension, and so on.

In [30]:
# to find no.of dimensions

a = np.array([[2,4,8],
              [5,9,6],
              [5,8,2]])

print(a.ndim)

2


In [32]:
# to find shape of an array (no.of elements in matrix)
a = np.array([[[2,4,6],[4,7,9],
               [2,4,6],[4,8,3],
               [9,5,7],[3,9,1]]])
print(a.shape)


(1, 6, 3)


In [34]:
# to find the size of array (r&c)
a = np.array([[[2,4,6],[4,7,9],
               [2,4,6],[4,8,3],
               [9,5,7],[3,9,1]]])
print(a.size)


18


In [35]:
# to find len of matrix (no of rows)

arr = np.array([[32,56,23],
                [43,56,32],
                [54,34,25]])

print(len(arr))

3


In [36]:
# to know the data type

a.dtype

dtype('int64')

# **numpy array indexind**

  - NumPy indexing is used for accessing an element from an array by giving it an index value that starts from 0.

In [37]:
# access of array elements
# 1D
a = np.array([4,4,7,1,7,9,578])
print(a[5])

9


In [40]:
# Access 2D arrays
arr = np.array([[32,56,23],
                [43,56,32],
                [54,34,25]])

print(arr[2,1])
print(arr[1,2])

34
32


In [50]:
# access 3D arrays

arr = np.array([[[2,4,6],[4,7,9]],
              [[2,4,6],[4,8,3]],
               [[9,5,7],[3,9,1]]])
print(arr[2,1,1])



9


# **Data types in numpy**


   - NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

   - Below is a list of all data types in NumPy and the characters used to represent them.

     - i - integer
     - b - boolean
     - u - unsigned integer
     - f - float
     - c - complex float
     - m - timedelta
     - M - datetime
     - O - object
     - S - string
     - U - unicode string
     - V - fixed chunk of memory for other type ( void )



In [52]:
# integer

arr = np.array([2,4,7,9],dtype='i')

print(arr)
print(arr.dtype)

[2 4 7 9]
int32


In [54]:
# string

arr = np.array([2,4,7,9],dtype='S')

print(arr)
print(arr.dtype)

[b'2' b'4' b'7' b'9']
|S1


# **converting data type on existing arrays in numpy**

   - The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

   -  The data type can be specified using a string, like 'f' for float, 'i' for integer etc.

   - or you can use the data type directly like float for float and int for integer.

In [58]:
# change data type from float to int by using 'i' as parameter.
import numpy as np

fl = np.array([1.2, 5.6, 6.1, 7.8])

i = fl.astype('i')

print(i)
print(i.dtype)

[1 5 6 7]
int32


In [61]:
# int to bool
i = np.array([-43,34,78,0,32,-3,2+2j,0])

b = i.astype(bool)

print(b)
print(b.dtype)

[ True  True  True False  True  True  True False]
bool


In [62]:
# int to float

i = np.array([2,4,67,8,3,78,674,34,98])

f = i.astype('f')

print(f)
print(f.dtype)


[  2.   4.  67.   8.   3.  78. 674.  34.  98.]
float32


# numpy array copy vs view.

   - The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

   - The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

   - The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [63]:
import numpy as np

#The copy should not be affected by the changes made to the original array.

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 54

print(arr)
print(x)

[54  2  3  4  5]
[1 2 3 4 5]


In [64]:
# shape
a = np.array([[3,4,5],
              [5,7,8],
              [8,9,3]])
print(a.shape)

(3, 3)


# Reshaping array

   - Using arr.reshape() will give a new shape to an array without changing the data.
   -  the reshape method, the array we want to produce needs to have the same number of elements as the original array.

In [65]:
a=np.arange(10)
print(a)

#Convert the following 1-D array with 12 elements into a 2-D array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 11, 9, 10, 11, 12, 13, 14])

newarr = arr.reshape(7, 2)

print(newarr)

[0 1 2 3 4 5 6 7 8 9]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7 11]
 [ 9 10]
 [11 12]
 [13 14]]


In [66]:
#Convert the following 1-D array with 12 elements into a 3-D arrray

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 2, 3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [67]:
#Convert the following 2-D array with 12 elements into a 1-D arrray

arr = np.array([[1, 2, 3, 4],
    [5, 6, 7, 8],[ 9, 10, 11, 12]])

newarr = arr.reshape(12)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [68]:
#Convert the following 2-D array with 12 elements into a 3-D arrray

arr = np.array([[1, 2, 3, 4],
    [5, 6, 7, 8],[ 9, 10, 11, 12]])

newarr = arr.reshape(1,4,3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [69]:
#Convert the following 3-D array with 12 elements into a 2-D arrray
arr = np.array([[[1, 2, 3, 4]],
    [[5, 6, 7, 8]],[[ 9, 10, 11, 12]]])

newarr = arr.reshape(3,4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
#Convert the following 3-D array with 12 elements into a 1-D arrray
arr = np.array([[[1, 2, 3, 4]],
    [[5, 6, 7, 8]],[[ 9, 10, 11, 12]]])

newarr = arr.reshape(12)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [72]:


# Python Program to create
# a data type object
x = np.array([[5,2],[3,12]])
y = np.array([[2,9],[4,8]])

In [73]:
# Addition of two Arrays
print(x + y)
print(np.add(x, y))

[[ 7 11]
 [ 7 20]]
[[ 7 11]
 [ 7 20]]


In [74]:
# subtract of the elements
print(x - y)
print(np.subtract(x, y))

#multiplication or  product
print(x * y)
print(np.multiply(x, y))

#division
print(x / y)
print(np.divide(x, y))

#square root
print(np.sqrt(x))
print(np.sqrt(y))

[[ 3 -7]
 [-1  4]]
[[ 3 -7]
 [-1  4]]
[[10 18]
 [12 96]]
[[10 18]
 [12 96]]
[[2.5        0.22222222]
 [0.75       1.5       ]]
[[2.5        0.22222222]
 [0.75       1.5       ]]
[[2.23606798 1.41421356]
 [1.73205081 3.46410162]]
[[1.41421356 3.        ]
 [2.         2.82842712]]


# NumPy Array Slicing

   - Slicing in python means taking elements from one given index to another given index.

   - We pass slice instead of index like this: [start:end].

   - We can also define the step, like this: [start:end:step].

   - If we don't pass start its considered 0

   - If we don't pass end its considered length of array in that dimension

   - If we don't pass step its considered 1

In [75]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:4])

[1 2 3 4]


In [76]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:-3])


arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-4:-3])


[1 2 3 4]
[4]


In [77]:
# Slicing 2-D Arrays

import numpy as np

arr = np.array([[1, 2, 3, 4, 5],   #0
                [6, 7, 8, 9, 10]])  #1

print(arr[1, 1:4])

[7 8 9]


In [79]:
arr = np.array([[1, 2, 3, 4, 5],   #0

                [6, 7, 8, 9, 10]])  #1

print(arr[1:2, 1])

[7]


In [78]:
            #0  #1 #2
a = np.array([[3, 4, 5],  #0
              [5, 7, 8],  #1
              [8, 9, 3],
              [4,7,8]])
print(a[2:3,1:3])


[[9 3]]


In [80]:
a = np.array([[13, 9, 35],  #0
              [58, 74, 88],  #1
              [88, 98, 3]]) #2
print(a[1:3,1:2])

[[74]
 [98]]


In [81]:
a = np.array([[[[13, 9, 35]]],  #0
              [[[58, 74, 88]]],  #1
              [[[88, 98, 3]]]]) #2
print(a[0:1])

[[[[13  9 35]]]]
